### ISSUE TITLE
Test initial issue

### ISSUE THREAD

**Issue by staticfloat** [jlbuild/jlbuild.jl#5]
@jlbuild ccb426f79af059ca6a83cd117350a3a7e067ba41 !filter=linux64

**Comment by jlbuild** [comment]
This is a test

**Comment by staticfloat** [comment]
@jlbuild 90cfb8292c5d8cdd25eb4b4653c03f6d382b42b1

**Comment by jlbuild** [comment]
## Status of https://github.com/JuliaLang/julia/commit/90cfb8292c5d8cdd25eb4b4653c03f6d382b42b1 builds:

| Builder Name | Build | Download |
| :----------- | :---: | :------: |
| linux32 | [COMPLETE](https://buildtest.e.ip.saba.us/#/builders/33/builds/11) | [Download](https://julianightlies.s3.amazonaws.com/test/bin/linux/x86/0.6/julia-90cfb8292c-linux32.tar.gz) | N/A |
| linux64 | [COMPLETE](https://buildtest.e.ip.saba.us/#/builders/10/builds/13) | [Download](https://julianightlies.s3.amazonaws.com/test/bin/linux/x64/0.6/julia-90cfb8292c-linux64.tar.gz) | N/A |
| linuxaarch64 | [COMPLETE](https://buildtest.e.ip.saba.us/#/builders/58/builds/15) | [Download](https://julianightlies.s3.amazonaws.com/test/bin/linux/aarch64/0.6/julia-90cfb8292c-linuxaarch64.tar.gz) | N/A |
| linuxarmv7l | [COMPLETE](https://buildtest.e.ip.saba.us/#/builders/3/builds/14) | [Download](https://julianightlies.s3.amazonaws.com/test/bin/linux/armv7l/0.6/julia-90cfb8292c-linuxarmv7l.tar.gz) | N/A |
| linuxppc64le | [COMPLETE](https://buildtest.e.ip.saba.us/#/builders/18/builds/17) | [Download](https://julianightlies.s3.amazonaws.com/test/bin/linux/ppc64le/0.6/julia-90cfb8292c-linuxppc64.tar.gz) | N/A |
| osx64 | [ERRORED](https://buildtest.e.ip.saba.us/#/builders/1/builds/8) | N/A | N/A |
| win32 | [PENDING](https://buildtest.e.ip.saba.us/#/buildrequests/195) | N/A | N/A |
| win64 | [PENDING](https://buildtest.e.ip.saba.us/#/buildrequests/196) | N/A | N/A |

**Comment by staticfloat** [comment]
@jlbuild 90cfb8292c5d8cdd25eb4b4653c03f6d382b42b1

**Comment by jlbuild** [comment]
## Status of https://github.com/JuliaLang/julia/commit/90cfb8292c5d8cdd25eb4b4653c03f6d382b42b1 builds:

| Builder Name | Build | Download |
| :----------- | :---: | :------: |
| linux32 | [COMPLETE](https://buildtest.e.ip.saba.us/#/builders/33/builds/12) | [Download](https://julianightlies.s3.amazonaws.com/test/bin/linux/x86/0.6/julia-90cfb8292c-linux32.tar.gz) | N/A |
| linux64 | [COMPLETE](https://buildtest.e.ip.saba.us/#/builders/10/builds/14) | [Download](https://julianightlies.s3.amazonaws.com/test/bin/linux/x64/0.6/julia-90cfb8292c-linux64.tar.gz) | N/A |
| linuxaarch64 | [COMPLETE](https://buildtest.e.ip.saba.us/#/builders/58/builds/16) | [Download](https://julianightlies.s3.amazonaws.com/test/bin/linux/aarch64/0.6/julia-90cfb8292c-linuxaarch64.tar.gz) | N/A |
| linuxarmv7l | [COMPLETE](https://buildtest.e.ip.saba.us/#/builders/3/builds/15) | [Download](https://julianightlies.s3.amazonaws.com/test/bin/linux/armv7l/0.6/julia-90cfb8292c-linuxarmv7l.tar.gz) | N/A |
| linuxppc64le | [COMPLETE](https://buildtest.e.ip.saba.us/#/builders/18/builds/18) | [Download](https://julianightlies.s3.amazonaws.com/test/bin/linux/ppc64le/0.6/julia-90cfb8292c-linuxppc64.tar.gz) | N/A |
| osx64 | [ERRORED](https://buildtest.e.ip.saba.us/#/builders/1/builds/9) | N/A | N/A |
| win32 | [PENDING](https://buildtest.e.ip.saba.us/#/buildrequests/203) | N/A | N/A |
| win64 | [PENDING](https://buildtest.e.ip.saba.us/#/buildrequests/204) | N/A | N/A |

**Comment by staticfloat** [comment]
@jlbuild 90cfb8292c5d8cdd25eb4b4653c03f6d382b42b1 !nuke
```
Base.versioninfo()
```

**Comment by jlbuild** [comment]
## Status of https://github.com/JuliaLang/julia/commit/90cfb8292c5d8cdd25eb4b4653c03f6d382b42b1 builds:

| Builder Name | Nuke | Build | Download | Code Output |
| :----------- | :--: | :---: | :------: | :---------: |
| linux32 | [COMPLETE](https://buildtest.e.ip.saba.us/#/builders/51/builds/8) | [COMPLETE](https://buildtest.e.ip.saba.us/#/builders/33/builds/13) | [Download](https://julianightlies.s3.amazonaws.com/test/bin/linux/x86/0.6/julia-90cfb8292c-linux32.tar.gz) | [COMPLETE](https://buildtest.e.ip.saba.us/#/builders/37/builds/4) |
| linux64 | [COMPLETE](https://buildtest.e.ip.saba.us/#/builders/57/builds/10) | [COMPLETE](https://buildtest.e.ip.saba.us/#/builders/10/builds/15) | [Download](https://julianightlies.s3.amazonaws.com/test/bin/linux/x64/0.6/julia-90cfb8292c-linux64.tar.gz) | [COMPLETE](https://buildtest.e.ip.saba.us/#/builders/4/builds/5) |
| linuxaarch64 | [COMPLETE](https://buildtest.e.ip.saba.us/#/builders/56/builds/8) | [COMPLETE](https://buildtest.e.ip.saba.us/#/builders/58/builds/17) | [Download](https://julianightlies.s3.amazonaws.com/test/bin/linux/aarch64/0.6/julia-90cfb8292c-linuxaarch64.tar.gz) | [COMPLETE](https://buildtest.e.ip.saba.us/#/builders/36/builds/7) |
| linuxarmv7l | [COMPLETE](https://buildtest.e.ip.saba.us/#/builders/49/builds/9) | [COMPLETE](https://buildtest.e.ip.saba.us/#/builders/3/builds/16) | [Download](https://julianightlies.s3.amazonaws.com/test/bin/linux/armv7l/0.6/julia-90cfb8292c-linuxarmv7l.tar.gz) | [COMPLETE](https://buildtest.e.ip.saba.us/#/builders/35/builds/5) |
| linuxppc64le | [COMPLETE](https://buildtest.e.ip.saba.us/#/builders/24/builds/14) | [COMPLETE](https://buildtest.e.ip.saba.us/#/builders/18/builds/19) | [Download](https://julianightlies.s3.amazonaws.com/test/bin/linux/ppc64le/0.6/julia-90cfb8292c-linuxppc64.tar.gz) | [COMPLETE](https://buildtest.e.ip.saba.us/#/builders/2/builds/6) |
| osx64 | [COMPLETE](https://buildtest.e.ip.saba.us/#/builders/59/builds/6) | [COMPLETE](https://buildtest.e.ip.saba.us/#/builders/1/builds/10) | [Download](https://julianightlies.s3.amazonaws.com/test/bin/mac/x64/0.6/julia-90cfb8292c-mac64.dmg) | [ERRORED](https://buildtest.e.ip.saba.us/#/builders/55/builds/7) |
| win32 | [PENDING](https://buildtest.e.ip.saba.us/#/buildrequests/211) | N/A | N/A | N/A |
| win64 | [PENDING](https://buildtest.e.ip.saba.us/#/buildrequests/212) | N/A | N/A | N/A |
