### ISSUE TITLE
testing

### ISSUE THREAD

**Issue by staticfloat** [jlbuild/jlbuild.jl#6]
@jlbuild 97efa2b4dec6133b0d69ea78ac0c9b284dce20c4
```julia
@show filter(x -> contains(x, "libgfortran"), Libdl.dllist())
```

**Comment by jlbuild** [comment]
## Status of https://github.com/JuliaLang/julia/commit/97efa2b4dec6133b0d69ea78ac0c9b284dce20c4 builds:

| Builder Name | Build | Download | Code Output |
| :----------- | :---: | :------: | :---------: |
| linux32 | [COMPLETE](https://buildog.julialang.org/#/builders/40/builds/9) | [Download](https://julialangnightlies.s3.amazonaws.com/test/bin/linux/x86/0.6/julia-97efa2b4de-linux32.tar.gz) | [COMPLETE](https://buildog.julialang.org/#/builders/44/builds/2) |
| linux64 | [COMPLETE](https://buildog.julialang.org/#/builders/35/builds/12) | [Download](https://julialangnightlies.s3.amazonaws.com/test/bin/linux/x64/0.6/julia-97efa2b4de-linux64.tar.gz) | [COMPLETE](https://buildog.julialang.org/#/builders/5/builds/3) |
| linuxaarch64 | [COMPLETE](https://buildog.julialang.org/#/builders/65/builds/9) | [Download](https://julialangnightlies.s3.amazonaws.com/test/bin/linux/aarch64/0.6/julia-97efa2b4de-linuxaarch64.tar.gz) | [COMPLETE](https://buildog.julialang.org/#/builders/43/builds/3) |
| linuxarmv7l | [ERRORED](https://buildog.julialang.org/#/builders/4/builds/10) | N/A | N/A |
| linuxppc64le | [COMPLETE](https://buildog.julialang.org/#/builders/20/builds/9) | [Download](https://julialangnightlies.s3.amazonaws.com/test/bin/linux/ppc64le/0.6/julia-97efa2b4de-linuxppc64.tar.gz) | [COMPLETE](https://buildog.julialang.org/#/builders/6/builds/3) |
| osx64 | [ERRORED](https://buildog.julialang.org/#/builders/1/builds/10) | N/A | N/A |
| win32 | [PENDING](https://buildog.julialang.org/#/buildrequests/144) | N/A | N/A |
| win64 | [CANCELED](https://buildog.julialang.org/#/buildrequests/141) | N/A | N/A |

**Comment by staticfloat** [comment]
@jlbuild 97efa2b4dec6133b0d69ea78ac0c9b284dce20c4
```julia
println(filter(x -> contains(x, "libgfortran"), Libdl.dllist()))
println(readdir(joinpath(Base.JULIA_HOME, "../lib/julia")))
```

**Comment by jlbuild** [comment]
## Status of https://github.com/JuliaLang/julia/commit/97efa2b4dec6133b0d69ea78ac0c9b284dce20c4 builds:

| Builder Name | Build | Download | Code Output |
| :----------- | :---: | :------: | :---------: |
| linux32 | N/A | N/A | [COMPLETE](https://buildog.julialang.org/#/builders/44/builds/3) |
| linux64 | N/A | N/A | [COMPLETE](https://buildog.julialang.org/#/builders/5/builds/4) |
| linuxaarch64 | N/A | N/A | [COMPLETE](https://buildog.julialang.org/#/builders/43/builds/4) |
| linuxarmv7l | [ERRORED](https://buildog.julialang.org/#/builders/4/builds/11) | N/A | N/A |
| linuxppc64le | N/A | N/A | [COMPLETE](https://buildog.julialang.org/#/builders/6/builds/4) |
| osx64 | [COMPLETE](https://buildog.julialang.org/#/builders/1/builds/11) | [Download](https://julialangnightlies.s3.amazonaws.com/test/bin/mac/x64/0.6/julia-97efa2b4de-mac64.dmg) | [COMPLETE](https://buildog.julialang.org/#/builders/61/builds/3) |
| win32 | [PENDING](https://buildog.julialang.org/#/buildrequests/156) | N/A | N/A |
| win64 | [CANCELED](https://buildog.julialang.org/#/buildrequests/153) | N/A | N/A |

**Comment by staticfloat** [comment]
@jlbuild b50fae946f
```julia
println(filter(x -> contains(x, "libgfortran"), Libdl.dllist()))
println(readdir(joinpath(Base.JULIA_HOME, "../lib/julia")))
```

**Comment by jlbuild** [comment]
## Status of https://github.com/JuliaLang/julia/commit/b50fae946fcba35647ad6142039f545cba9edc2b builds:

| Builder Name | Build | Download | Code Output |
| :----------- | :---: | :------: | :---------: |
| linux32 | [COMPLETE](https://buildog.julialang.org/#/builders/40/builds/10) | [Download](https://julialangnightlies.s3.amazonaws.com/test/bin/linux/x86/0.7/julia-b50fae946f-linux32.tar.gz) | [COMPLETE](https://buildog.julialang.org/#/builders/44/builds/4) |
| linux64 | [COMPLETE](https://buildog.julialang.org/#/builders/35/builds/13) | [Download](https://julialangnightlies.s3.amazonaws.com/test/bin/linux/x64/0.7/julia-b50fae946f-linux64.tar.gz) | [COMPLETE](https://buildog.julialang.org/#/builders/5/builds/5) |
| linuxaarch64 | [COMPLETE](https://buildog.julialang.org/#/builders/65/builds/10) | [Download](https://julialangnightlies.s3.amazonaws.com/test/bin/linux/aarch64/0.7/julia-b50fae946f-linuxaarch64.tar.gz) | [COMPLETE](https://buildog.julialang.org/#/builders/43/builds/5) |
| linuxarmv7l | [ERRORED](https://buildog.julialang.org/#/builders/4/builds/12) | N/A | N/A |
| linuxppc64le | [COMPLETE](https://buildog.julialang.org/#/builders/20/builds/10) | [Download](https://julialangnightlies.s3.amazonaws.com/test/bin/linux/ppc64le/0.7/julia-b50fae946f-linuxppc64.tar.gz) | [COMPLETE](https://buildog.julialang.org/#/builders/6/builds/5) |
| osx64 | [COMPLETE](https://buildog.julialang.org/#/builders/1/builds/12) | [Download](https://julialangnightlies.s3.amazonaws.com/test/bin/mac/x64/0.7/julia-b50fae946f-mac64.dmg) | [COMPLETE](https://buildog.julialang.org/#/builders/61/builds/4) |
| win32 | [PENDING](https://buildog.julialang.org/#/buildrequests/164) | N/A | N/A |
| win64 | [CANCELED](https://buildog.julialang.org/#/buildrequests/161) | N/A | N/A |

**Comment by staticfloat** [comment]
@jlbuild 116741d68fac3c86699bdb79dbf6ad2b2d2f55ce
```julia
println(filter(x -> contains(x, "libgfortran"), Libdl.dllist()))
println(readdir(joinpath(Base.JULIA_HOME, "../lib/julia")))
```

**Comment by jlbuild** [comment]
## Status of https://github.com/JuliaLang/julia/commit/116741d68fac3c86699bdb79dbf6ad2b2d2f55ce builds:

| Builder Name | Build | Download | Code Output |
| :----------- | :---: | :------: | :---------: |
| linux32 | [COMPLETE](https://buildog.julialang.org/#/builders/40/builds/11) | [Download](https://julialangnightlies.s3.amazonaws.com/test/bin/linux/x86/0.7/julia-116741d68f-linux32.tar.gz) | [COMPLETE](https://buildog.julialang.org/#/builders/44/builds/5) |
| linux64 | [COMPLETE](https://buildog.julialang.org/#/builders/35/builds/14) | [Download](https://julialangnightlies.s3.amazonaws.com/test/bin/linux/x64/0.7/julia-116741d68f-linux64.tar.gz) | [COMPLETE](https://buildog.julialang.org/#/builders/5/builds/6) |
| linuxaarch64 | [COMPLETE](https://buildog.julialang.org/#/builders/65/builds/11) | [Download](https://julialangnightlies.s3.amazonaws.com/test/bin/linux/aarch64/0.7/julia-116741d68f-linuxaarch64.tar.gz) | [COMPLETE](https://buildog.julialang.org/#/builders/43/builds/6) |
| linuxarmv7l | [ERRORED](https://buildog.julialang.org/#/builders/4/builds/14) | N/A | N/A |
| linuxppc64le | [COMPLETE](https://buildog.julialang.org/#/builders/20/builds/11) | [Download](https://julialangnightlies.s3.amazonaws.com/test/bin/linux/ppc64le/0.7/julia-116741d68f-linuxppc64.tar.gz) | [COMPLETE](https://buildog.julialang.org/#/builders/6/builds/6) |
| osx64 | [COMPLETE](https://buildog.julialang.org/#/builders/1/builds/15) | [Download](https://julialangnightlies.s3.amazonaws.com/test/bin/mac/x64/0.7/julia-116741d68f-mac64.dmg) | [COMPLETE](https://buildog.julialang.org/#/builders/61/builds/6) |
| win32 | [PENDING](https://buildog.julialang.org/#/buildrequests/182) | N/A | N/A |
| win64 | [CANCELED](https://buildog.julialang.org/#/buildrequests/179) | N/A | N/A |

**Comment by staticfloat** [comment]
@jlbuild v0.6.0-rc2 !nuke !filter=win !flags=LIBUV_SHA1=f457c0999,LIBUV_BRANCH=sf/win_pipe,DEPS_GIT=1

**Comment by staticfloat** [comment]
@jlbuild 68e911be5 !nuke !filter=win !flags=LIBUV_SHA1=f457c0999,LIBUV_BRANCH=sf/win_pipe,DEPS_GIT=1

**Comment by jlbuild** [comment]
## Status of https://github.com/JuliaLang/julia/commit/68e911be534f84f6201cbdd5d92ef0757af1238a builds:

| Builder Name | Nuke | Build | Download |
| :----------- | :--: | :---: | :------: |
| win32 | [CANCELED](https://buildog.julialang.org/#/buildrequests/311) | N/A | N/A | N/A |
| win64 | [COMPLETE](https://buildog.julialang.org/#/builders/55/builds/5) | [ERRORED](https://buildog.julialang.org/#/builders/74/builds/24) | N/A | N/A |

**Comment by staticfloat** [comment]
@jlbuild v0.6.0-rc2

**Comment by jlbuild** [comment]
Got it, building https://github.com/JuliaLang/julia/commit/68e911be534f84f6201cbdd5d92ef0757af1238a

I will edit this comment as the build jobs complete.

**Comment by jlbuild** [comment]
## Status of https://github.com/JuliaLang/julia/commit/68e911be534f84f6201cbdd5d92ef0757af1238a builds:

| Builder Name | Build | Download |
| :----------- | :---: | :------: |
| linux32 | [COMPLETE](https://buildog.julialang.org/#/builders/41/builds/28) | [Download](https://julialangnightlies.s3.amazonaws.com/test/bin/linux/x86/0.6/julia-68e911be53-linux32.tar.gz) | N/A |
| linux64 | [ERRORED](https://buildog.julialang.org/#/builders/38/builds/30) | N/A | N/A |
| linuxaarch64 | [COMPLETE](https://buildog.julialang.org/#/builders/69/builds/33) | [Download](https://julialangnightlies.s3.amazonaws.com/test/bin/linux/aarch64/0.6/julia-68e911be53-linuxaarch64.tar.gz) | N/A |
| linuxarmv7l | [ERRORED](https://buildog.julialang.org/#/builders/4/builds/33) | N/A | N/A |
| linuxppc64le | [COMPLETE](https://buildog.julialang.org/#/builders/20/builds/31) | [Download](https://julialangnightlies.s3.amazonaws.com/test/bin/linux/ppc64le/0.6/julia-68e911be53-linuxppc64.tar.gz) | N/A |
| osx64 | [COMPLETE](https://buildog.julialang.org/#/builders/1/builds/27) | [Download](https://julialangnightlies.s3.amazonaws.com/test/bin/mac/x64/0.6/julia-68e911be53-mac64.dmg) | N/A |
| win32 | [PENDING](https://buildog.julialang.org/#/buildrequests/445) | N/A | N/A |
| win64 | [ERRORED](https://buildog.julialang.org/#/builders/74/builds/34) | N/A | N/A |

**Comment by staticfloat** [comment]
@jlbuild v0.6.0-rc3

**Comment by staticfloat** [comment]
@jlbuild v0.6.0-rc3

**Comment by jlbuild** [comment]
## Status of https://github.com/JuliaLang/julia/commit/ad290e93e4d10831c1be42cc706babaaeb49c19c builds:

| Builder Name | Build | Download |
| :----------- | :---: | :------: |
| linux32 | [COMPLETE](https://buildog.julialang.org/#/builders/41/builds/48) | [Download](https://julialangnightlies.s3.amazonaws.com/test/bin/linux/x86/0.6/julia-ad290e93e4-linux32.tar.gz) | N/A |
| linux64 | [COMPLETE](https://buildog.julialang.org/#/builders/38/builds/51) | [Download](https://julialangnightlies.s3.amazonaws.com/test/bin/linux/x64/0.6/julia-ad290e93e4-linux64.tar.gz) | N/A |
| linuxaarch64 | N/A | N/A | N/A |
| linuxarmv7l | N/A | N/A | N/A |
| linuxppc64le | [PENDING](https://buildog.julialang.org/#/buildrequests/685) | N/A | N/A |
| osx64 | [COMPLETE](https://buildog.julialang.org/#/builders/1/builds/49) | [Download](https://julialangnightlies.s3.amazonaws.com/test/bin/mac/x64/0.6/julia-ad290e93e4-mac64.dmg) | N/A |
| win32 | [PENDING](https://buildog.julialang.org/#/buildrequests/689) | N/A | N/A |
| win64 | [PENDING](https://buildog.julialang.org/#/buildrequests/687) | N/A | N/A |

**Comment by jlbuild** [comment]
## Status of https://github.com/JuliaLang/julia/commit/ad290e93e4d10831c1be42cc706babaaeb49c19c builds:

| Builder Name | Build | Download |
| :----------- | :---: | :------: |
| linux32 | [COMPLETE](https://buildog.julialang.org/#/builders/41/builds/49) | [Download](https://julialangnightlies.s3.amazonaws.com/test/bin/linux/x86/0.6/julia-ad290e93e4-linux32.tar.gz) | N/A |
| linux64 | [COMPLETE](https://buildog.julialang.org/#/builders/38/builds/52) | [Download](https://julialangnightlies.s3.amazonaws.com/test/bin/linux/x64/0.6/julia-ad290e93e4-linux64.tar.gz) | N/A |
| linuxaarch64 | N/A | N/A | N/A |
| linuxarmv7l | N/A | N/A | N/A |
| linuxppc64le | [PENDING](https://buildog.julialang.org/#/buildrequests/691) | N/A | N/A |
| osx64 | [COMPLETE](https://buildog.julialang.org/#/builders/1/builds/50) | [Download](https://julialangnightlies.s3.amazonaws.com/test/bin/mac/x64/0.6/julia-ad290e93e4-mac64.dmg) | N/A |
| win32 | [PENDING](https://buildog.julialang.org/#/buildrequests/695) | N/A | N/A |
| win64 | [PENDING](https://buildog.julialang.org/#/buildrequests/693) | N/A | N/A |
