### ISSUE TITLE
Init testing

### ISSUE THREAD

**Issue by staticfloat** [jlbuild/jlbuild.jl#8]
@jlbuild master

**Comment by jlbuild** [comment]
I'm sorry, I couldn't parse out any valid commands from your comment.
Please see my [README](https://github.com/jlbuild/jlbuild.jl) for instructions on how to use me.

**Comment by jlbuild** [comment]
I'm sorry, I couldn't parse out any valid commands from your comment.
Please see my [README](https://github.com/jlbuild/jlbuild.jl) for instructions on how to use me.
